package orar.dlfragmentvalidator;

public enum DLConstructor {
	NOMINAL, HASVALUE, //
	CONJUNCTION, Horn_DISJUNCTION, NonHorn_DISJUNCTION, NonHorn_NEGATION, //
	FUNCTIONALITY, //
	MAX_CARDINALITY_LEFT, MAX_CARDINALITY_RIGHT, //
	MIN_CARDINALITY, EXISTENTIAL_RESTRICTION, //
	UNIVERSAL_RESTRICTION, NonHorn_UNIVERSAL_RESTRICTION, DATATYPE, TRANSITIVITY, //
	ROLECHAIN, REFLEXSIVEROLE, //
	DOMAIN, RANGE;
}
