package orar.dlfragmentvalidator;

public enum DLConstructor {
	NOMINAL, HASVALUE, //
	CONJUNCTION, Horn_DISJUNCTION, NonHorn_DISJUNCTION, NonHorn_NEGATION, DISJUNCTION,NEGATION,//
	FUNCTIONALITY, INVERSE_FUNCTIONALITY,//
	MAX_CARDINALITY_LEFT, MAX_CARDINALITY_RIGHT, //
	MIN_CARDINALITY,// 
	EXISTENTIAL_RESTRICTION, QUALIFIED_EXISTENTIAL_RESTRICTION, UNQUALIFIED_EXISTENTIAL_RESTRICTION,//
	UNIVERSAL_RESTRICTION, NonHorn_UNIVERSAL_RESTRICTION, DATATYPE, TRANSITIVITY, //
	ROLECHAIN, REFLEXSIVEROLE, //
	DOMAIN_CONSTRAIN_OF_ROLE, RANGE_CONSTRAIN_OF_ROLE, EQUIVALENT_TO_RANGE_CONSTRAIN,//
	EQUIVALENT_ROLE, SUB_ROLE, SYMMETRIC_ROLE, INVERSE_ROLE;
}
