package orar.config;

public enum DebugLevel {
	MERGING_INDIVIDUALS_DIRECTLY, MERGING_INDIVIDUALS_BYABSTRACTION, DL_FRAGMENT_VALIDATING, //
	REASONING, ABSTRACTION_CREATION, MARKING_INDIVIDUALS_TOCHECK_SAMEAS, UPDATING_CONCEPT_ASSERTION, //
	NORMALIZATION, TYPE_COMPUTING, TRANSITIVITY_ELIMINATION, MARKING_INDIVIDUAL_OF_SINGLETONCONCEPT_AND_HAVINGCOUNTINGCONCEPT, //
	REASONING_ABSTRACTONTOLOGY, ADDING_MARKING_AXIOMS, STREAM_PARSING, PRINT_MARKING_INDIVIDUALS,//
	TRANSFER_SAMEAS, TRANSFER_ROLEASSERTION,TRANSFER_CONCEPTASSERTION;
}
