package orar.config;

public enum LogInfo {
	NORMALIZATION_INFO, LANGUAGE_VALIDATION_INFO, ABSTRACT_ONT_INFO, ABSTRACTION_INFO, INPUTONTOLOGY_INFO, TYPE_COMPUTING_INFO, LOADING_TIME, REASONING_TIME, TOTAL_TIME, TYPE_INFO, COMPARED_RESULT_INFO, STATISTIC, ABSTRACT_EXPLANATION;
}
